log_level: WARNING
severity: # Minor, Moderate, Severe, Extreme, Unknown
- Moderate
- Severe
- Extreme
sleep_interval:
  normal: 300.0
  urgent: 60.0
status_api: true
zones: # Public, county and/or fire zone IDs. see all_zones.csv or use the web UI
- TXC001
