zones:
  # Add more zone IDs as needed. At least one zone is required.
  - TXC235

severity:   # Unknown, Minor, Moderate, Severe, Extreme
  #- Unknown
  #- Minor
  - Moderate
  - Severe
  - Extreme

log_level: WARNING  # DEBUG, INFO, WARNING, ERROR

sleep_interval:
  normal: 300.0  # seconds
  urgent: 60.0